# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1dc99a4b-a7e9-4e7d-88ce-72e0c0a89597";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8B58-4304";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/541f40d7-e6ee-41f8-a18a-08d8292de732"; }
    ];

  fileSystems."/media" =
    {
      device = "/dev/disk/by-uuid/9e3f6c83-ba13-45c2-92bd-03eac60f7f73";
      fsType = "ext4";
    };

  fileSystems."/media2" =
    { device = "/dev/disk/by-uuid/ba5e3bdc-dca8-4890-8a9e-19091088351f";
      fsType = "ext4";
    };

  fileSystems."/media3" =
    { device = "/dev/disk/by-uuid/42c7cd1f-42e6-459c-b584-187d604816af";
      fsType = "ext4";
    };

  fileSystems."/games" =
    {
      device = "/dev/disk/by-uuid/49b06da0-3c95-46a0-9c05-0bc31b144f9a";
    };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wg-mullvad.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
